dependencies:
  - aave/protocol-v2@1.0.1
  - smartcontractkit/chainlink@1.1.0
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@3.4.2
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
      - "@chainlink=smartcontractkit/chainlink@1.1.0"
      - "@chainlink-brownie=smartcontractkit/chainlink-brownie-contracts@0.3.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.2"

# dependencies:
#   - freddie71010/LinkToken@1.0.0
# compiler:
#   solc:
#     remappings:
#       - "@linktoken=freddie71010/LinkToken@1.0.0"

dotenv: .env
networks:
  default: mainnet-fork
  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
    lending_pool_address_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_address_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
wallets:
  MM1: ${MM1_PRIVATE_KEY}
  MM2: ${MM2_PRIVATE_KEY}
api_keys:
  etherscan: ${ETHERSCAN_TOKEN}