dependencies:
  - smartcontractkit/chainlink@1.1.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2
dotenv: .env
compiler:
  solc:
    version: 0.8.8
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.0"
      - "@chainlink-brownie=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
networks:
  default: mainnet-fork
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    